# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 198b0482d5ec22f3c080fa25e550fc36d417d3f078bf1f05c856fd78f42d2d7468e1bc6a76322cbfe4015eafa6e56a460eceeecfb11d3670192e2cd1dac7f1d1

test:
  secret_key_base: 79a60587e7d664c249d53c56c8d029ea224db39f79ca72143d8e2de7841994277e53472c9b9674fe4685a4591c504855171d045eec971486e21f17547196c4de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
