# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4bd0340981515aabc3d0347546c6cb57462843a997063c10f243849c9f815e9c13dfc1e15aec61dbf03e73ae9f157909d176567a61f6351208b920e1fdc23dd

test:
  secret_key_base: 76b9f22b9b91a84f265164f362691519d45bf1e9f62b126a8b634c7ed850326224cc209b61aff86b752b66947cd9d8f75725d791800555bda99b085ffa5f27a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
